caddy test

diff --git a/containers/caddy/2.7.6/Dockerfile b/containers/caddy/2.7.6/Dockerfile
--- a/containers/caddy/2.7.6/Dockerfile
+++ b/containers/caddy/2.7.6/Dockerfile
@@ -1,37 +1,16 @@
-# FROM caddy:2.7.4-alpine
+FROM caddy:2.7.4-alpine
 
-# RUN set -eux; \
-# 	apkArch="$(apk --print-arch)"; \
-# 	case "$apkArch" in \
-# 		x86_64)  binArch='amd64' ;; \
-# 		aarch64) binArch='arm64' ;; \
-# 		*) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;\
-# 	esac; \
-# 	wget -O caddy "https://github.com/igorferreir4/caddy/releases/download/v2.7.4/caddy-linux-${binArch}"; \
-# 	rm /usr/bin/caddy; \
-#     mv caddy /usr/bin; \
-#     chmod +x /usr/bin/caddy
-
-# # Change TZ to America/Sao_Paulo
-# RUN apk add --update --no-cache tzdata && \
-#     cp /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime && \
-#     echo "America/Sao_Paulo" >  /etc/timezone && \
-#     apk del tzdata && \
-#     rm -rf /var/cache/apk/*
-
-# CMD ["caddy", "docker-proxy"]
-
-FROM caddy:2.7.6-builder-alpine AS builder
-
-RUN xcaddy build \
-    --with github.com/caddy-dns/cloudflare \
-    --with github.com/WeidiDeng/caddy-cloudflare-ip \
-    --with github.com/mholt/caddy-l4 \
-    --with github.com/RussellLuo/caddy-ext/layer4
-
-FROM caddy:2.7.6-alpine
-
-COPY --from=builder /usr/bin/caddy /usr/bin/caddy
+RUN set -eux; \
+	apkArch="$(apk --print-arch)"; \
+	case "$apkArch" in \
+		x86_64)  binArch='amd64' ;; \
+		aarch64) binArch='arm64' ;; \
+		*) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;\
+	esac; \
+	wget -O caddy "https://github.com/igorferreir4/caddy/releases/download/v2.7.6/caddy-linux-${binArch}"; \
+	rm /usr/bin/caddy; \
+    mv caddy /usr/bin; \
+    chmod +x /usr/bin/caddy
 
 # Change TZ to America/Sao_Paulo
 RUN apk add --update --no-cache tzdata && \
@@ -39,3 +18,22 @@ RUN apk add --update --no-cache tzdata && \
     echo "America/Sao_Paulo" >  /etc/timezone && \
     apk del tzdata && \
     rm -rf /var/cache/apk/*
+
+# FROM caddy:2.7.6-builder-alpine AS builder
+
+# RUN xcaddy build \
+#     --with github.com/caddy-dns/cloudflare \
+#     --with github.com/WeidiDeng/caddy-cloudflare-ip \
+#     --with github.com/mholt/caddy-l4 \
+#     --with github.com/RussellLuo/caddy-ext/layer4
+
+# FROM caddy:2.7.6-alpine
+
+# COPY --from=builder /usr/bin/caddy /usr/bin/caddy
+
+# # Change TZ to America/Sao_Paulo
+# RUN apk add --update --no-cache tzdata && \
+#     cp /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime && \
+#     echo "America/Sao_Paulo" >  /etc/timezone && \
+#     apk del tzdata && \
+#     rm -rf /var/cache/apk/*
