Update Dockerfile

diff --git a/imagens/samba-server/Dockerfile b/imagens/samba-server/Dockerfile
--- a/imagens/samba-server/Dockerfile
+++ b/imagens/samba-server/Dockerfile
@@ -1,20 +1,17 @@
 FROM alpine:3.18 AS build
 
-ARG TARGETARCH
-
 ENV S6-VERSION=v3.1.5.0
 
 RUN apk add --no-cache openssl curl && \
-    ARCH= && \
-    Arch="${TARGETARCH}" && \
-    case "${Arch##*-}" in \
-    amd64|x86_64) ARCH='x86_64';; \
-    aarch64|arm64|arm/v8) ARCH='aarch64';; \
-    arm) ARCH='arm';; \
-    armhf|arm/v7) ARCH='armhf';; \
-    *) echo "unsupported architecture"; exit 1 ;; \
-  esac \
-  && curl -o /tmp/s6-overlay.tar.gz -fsSL --compressed https://github.com/just-containers/s6-overlay/releases/download/${S6-VERSION}/s6-overlay-${ARCH}.tar.gz
+    apkArch="$(apk --print-arch)"; \
+	  case "$apkArch" in \
+      amd64|x86_64) ARCH='x86_64';; \
+      arm) ARCH='arm';; \
+      armhf|arm/v7) ARCH='armhf';; \
+      aarch64|arm64|arm/v8) ARCH='aarch64';; \
+      *) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;\
+    esac; \
+    curl -o /tmp/s6-overlay.tar.gz -fsSL --compressed https://github.com/just-containers/s6-overlay/releases/download/${S6-VERSION}/s6-overlay-${ARCH}.tar.gz
 
 FROM alpine:3.18
 
